name: Build and Deploy React App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Ignorar erros do ESLint
      - name: Run ESLint (ignore errors)
        run: |
          npm run lint || true   # O || true garante que o erro não vai interromper o build

      - name: Build the app
        run: npm run build

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'YOUR_AZURE_APP_NAME'
